export const TOOL_ROUTES = [
  { path: '/', label: 'Weekly Report Tool', group: 'General' },
  { path: '/md-to-pdf', label: 'Markdown to PDF', group: 'PDF' },
  { path: '/pdf-merge', label: 'PDF Merger', group: 'PDF' },
  { path: '/pdf-split-extract', label: 'PDF Split & Extract', group: 'PDF' },
  { path: '/pdf-sign', label: 'PDF Signature', group: 'PDF' },
  { path: '/pdf-text-editor', label: 'PDF Text Editor', group: 'PDF' },
  { path: '/pdf-resize', label: 'PDF Resize', group: 'PDF' },
  { path: '/ebook-mockup', label: 'Ebook Mockup Creator', group: 'Design' },
  { path: '/m4a-to-mp3', label: 'M4A to MP3', group: 'Audio' },
  { path: '/html-editor', label: 'HTML Editor', group: 'Text & HTML' },
  { path: '/text-diff', label: 'Text Diff Checker', group: 'Text & HTML' },
  { path: '/json-formatter', label: 'JSON Formatter & Validator', group: 'Text & HTML' },
  { path: '/case-converter', label: 'Case Converter', group: 'Text & HTML' },
  { path: '/csv-to-xlsx', label: 'CSV to XLSX', group: 'Spreadsheet' },
  { path: '/csv-to-json', label: 'CSV to JSON', group: 'Spreadsheet' },
  { path: '/xlsx-to-csv', label: 'XLSX to CSV', group: 'Spreadsheet' },
]
